<?php
/**
 * Created by IntelliJ IDEA.
 * User: ColomboM
 * Date: 21/10/14
 * Time: 14:31
 */

 class MyExce extends Exception {

     /**
      *This method must return a string,
      * as otherwise a fatal E_RECOVERABLE_ERROR level error is emitted.
      */
     public function __toString()
     {
         //parent::__toString(); // Catchable fatal error: Method MyExce::__toString() must return a string value
         return parent::__toString(); // TODO: Change the autogenerated stub
     }
 }

 $e = new MyExce();
 //le eccezioni non si possono clonare
 //$e1 = clone $e;//PHP Fatal error:  Trying to clone an uncloneable object of class MyExce
 echo $e;